/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecontadortiempo.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import simplecontadortiempo.SimpleContadorTiempo;

/**
 *
 * @author Osvaldo
 */
public class SimpleContador extends javax.swing.JFrame {
    
    SimpleContadorTiempo contador = new SimpleContadorTiempo();
    Timer temporizador;

    /**
     * Creates new form SimpleContador
     */
    public SimpleContador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMinutos = new javax.swing.JLabel();
        labelSegundos = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnIniciar1 = new javax.swing.JButton();
        btnPausa1 = new javax.swing.JButton();
        labelMinutos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Temporizador - Versión A0.3");
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.black);

        labelMinutos.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMinutos.setForeground(new java.awt.Color(102, 102, 102));
        labelMinutos.setText("00");

        labelSegundos.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelSegundos.setForeground(new java.awt.Color(102, 102, 102));
        labelSegundos.setText("00");

        btnReiniciar.setText("Reset");
        btnReiniciar.setEnabled(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnIniciar1.setText("Iniciar");
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });

        btnPausa1.setText("Pausa");
        btnPausa1.setEnabled(false);
        btnPausa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausa1ActionPerformed(evt);
            }
        });

        labelMinutos1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMinutos1.setForeground(new java.awt.Color(102, 102, 102));
        labelMinutos1.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelMinutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMinutos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSegundos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPausa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciar)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinutos)
                    .addComponent(labelSegundos)
                    .addComponent(labelMinutos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar1)
                    .addComponent(btnReiniciar)
                    .addComponent(btnPausa1))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed

       actualizarContador("reset");
       btnIniciar1.setEnabled(true);
       btnPausa1.setEnabled(false);
       
       
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        
        actualizarContador("star");
        btnIniciar1.setEnabled(false);
        btnPausa1.setEnabled(true);
        btnReiniciar.setEnabled(true);
        
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    public void actualizarTitulo (String nuevoTitulo){
    this.setTitle(nuevoTitulo);
    }
    
    private void btnPausa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausa1ActionPerformed
        actualizarContador("stop");
        
    }//GEN-LAST:event_btnPausa1ActionPerformed

        public void actualizarContador(String tipo) {

        ActionListener accionActualizar = new ActionListener() {

            @Override

            public void actionPerformed(ActionEvent event) {

                contador.contarSegundos(labelSegundos, labelMinutos);
                String tituloDinamico = labelMinutos.getText() + " : "  + labelSegundos.getText();
                actualizarTitulo(tituloDinamico);
                

            }

        };


        if(tipo.equals("star"))
        {
        
            if(temporizador == null ){
            temporizador = new Timer(1000, accionActualizar);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Temporizador ya iniciado.");
            }
        
        }
        
        switch(tipo)
        {
            case "star"     : 
                temporizador.start();
            break;
            
            case "stop"     : 
                
                if(temporizador.isRunning()){
                temporizador.stop();
                }
                else
                {
                temporizador.start();
                }
                
            break;
            
            case "reset"   : 
                // temporizador.restart();
                contador.reiniciar(labelSegundos, labelMinutos);
                temporizador.stop();
                temporizador = null;
            break;
        }
        

    }
    

        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleContador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnPausa1;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel labelMinutos;
    private javax.swing.JLabel labelMinutos1;
    private javax.swing.JLabel labelSegundos;
    // End of variables declaration//GEN-END:variables
}
